version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@16.2.12
  build:
    commands:
      - echo "Building Angular reminder ui....."
      - ng build --configuration production
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/reminder-ui/ s3://reminder-ui --delete